name: tests

on:
  schedule:
    - cron: "0 4 * * 0"  # At 04:00 on Sunday.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [17, 21]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - run: mvn -T1C --batch-mode verify

  analyze:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v2
        with:
          languages: java
      - uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'adopt'
          cache: maven
      - run: mvn -T1C --batch-mode compile
      - uses: github/codeql-action/analyze@v2